import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import "./TeacherWorkspace.css";

export default function TeacherExtraPages() {
 const nav=useNavigate(), path=useLocation().pathname, type=path.split("/").pop();
 const [data,setData]=useState(null), [form,setForm]=useState(()=>JSON.parse(localStorage.getItem("teacherPreferences")||"{}"));
 useEffect(()=>{fetch("http://localhost:8080/api/teacher/dashboard",{headers:{Authorization:`Bearer ${localStorage.getItem("accessToken")}`}}).then(r=>r.json()).then(setData).catch(()=>setData({}));},[]);
 const title={reports:"Reports",calendar:"Calendar",settings:"Settings",profile:"Profile"}[type];
 const save=e=>{e.preventDefault();localStorage.setItem("teacherPreferences",JSON.stringify(form));alert("Saved on this device.");};
 return <main className="teacher-workspace"><header className="teacher-workspace-header"><div><p>TEACHER WORKSPACE</p><h1>{title}</h1><span>{type==="reports"?"Class-wise teaching summary":type==="calendar"?"Your timetable and class schedule":type==="settings"?"Manage your dashboard preferences":"View and update your profile details"}</span></div><button onClick={()=>nav("/teacher-dashboard")}>← Dashboard</button></header>{(type==="reports"||type==="calendar")&&<section className="teacher-workspace-card">{type==="reports"?<><h2>Class Reports</h2>{(data?.myClasses||[]).map(x=><div className="teacher-class-list" key={x.id}><article><time>{x.schedule||"Class"}</time><div><strong>{x.className}</strong><span>{x.course} · {x.studentCount||0} students</span></div></article></div>)}</>:<><h2>Today&apos;s Timetable</h2>{(data?.todaySchedule||[]).map(x=><div className="teacher-class-list" key={x.id}><article><time>{x.time}</time><div><strong>{x.subject}</strong><span>{x.branch} · Semester {x.semester}</span></div></article></div>)}</>}</section>}{(type==="settings"||type==="profile")&&<section className="teacher-workspace-card"><form className="teacher-create-form" onSubmit={save}>{type==="profile"&&<><label>Full Name<input value={form.name??data?.teacher?.name??""} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Department<input value={form.department??data?.teacher?.department??""} onChange={e=>setForm({...form,department:e.target.value})}/></label></>}<label>{type==="settings"?"Dashboard view":"Phone Number"}<input value={type==="settings"?(form.view||"Default"):(form.phone||"")} onChange={e=>setForm({...form,[type==="settings"?"view":"phone"]:e.target.value})}/></label><button>Save Changes</button></form></section>}</main>;
}
