package com.smartattendance.backend.dto;

import com.smartattendance.backend.entity.Role;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

/**
 * ==========================================================
 * Login Request DTO
 * ----------------------------------------------------------
 * This class receives login data from the frontend.
 * It is used during user authentication.
 * ==========================================================
 */

@Getter
@Setter
public class LoginRequest {

    // ======================================================
    // User Email
    // Used to identify the user during login.
    // ======================================================

    @Email(message = "Enter a valid Email Address")
    @NotBlank(message = "Email is required")
    private String email;

    // ======================================================
    // User Password
    // Used to verify user credentials.
    // ======================================================

    @NotBlank(message = "Password is required")
    private String password;

    // ======================================================
    // User Role
    // Allowed Values:
    // TEACHER
    // STUDENT
    // ======================================================

    @NotNull(message = "Role is required")
    private Role role;

    // ======================================================
    // Device ID
    // ------------------------------------------------------
    // Automatically generated by the frontend.
    //
    // Used only for Student accounts to enforce
    // One Device Login.
    //
    // Teacher login ignores this field.
    // ======================================================

    private String deviceId;
}